events{}

http {
    server {
        listen 80;

        location /reciever {
            proxy_pass http://reciever:8080;
        }

        location /storage {
            proxy_pass http://storage:8090;
        }

        location /processing {
            proxy_pass http://processing:8100;
        }

        location /analyzer {
            proxy_pass http://analyzer:8110;
        }

        location /anomaly_detector {
            proxy_pass http://anomaly_detector:8120;
        }

        location /check {
            proxy_pass http://check:8130;
        }

        location / {
            proxy_pass http://dashboard:3000;
        }
    }
}