{
 "title": "Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Messages Out ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (rate(kafka_consumergroup_current_offset[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (kafka_consumergroup_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_partition_current_offset[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (topic) (deriv(kafka_consumergroup_lag[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}