FROM python:3.11-slim AS builder
LABEL maintainer="lli249@my.bcit.ca"
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.11-slim
LABEL maintainer="lli249@my.bcit.ca"
WORKDIR /app
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
COPY . /app
ENTRYPOINT ["python3"]
CMD [ "app.py" ]
